config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  get "/productos", to: "home#products"
  resources :contacts, only: [:new, :create]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cliente.rb
class Cliente < ApplicationRecord
  validates :name, :email, presence: true

  after_save :send_purchase_email
  after_save :send_confirmation
  after_save :send_email

  private

  def send_purchase_email
  end

  def send_confirmation
  end

  def send_email
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  def create
  end

  def send_email
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def products
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="parallax" alt="team">
  <h1>FAVECECA</h1>
</div>

<div class="bio">
  <div class="bio-content" id="about-us-section">
    <div class="bio-content-symbol">
      <h1>_______</h1>
    </div>
    <div class="bio-content-title">
      <h2>Sobre Favececa</h2>
    </div>
    <div class="bio-content-story">
      <p> Favececa es una empresa dedicada a la fabricación de mallas tejidas hechas de acero con alto contenido de carbono, Con el objetivo de producir Cedazos de alta calidad y duraderos para Plantas de Asfalto, Clasificadoras de Arena, Piedra y Minerales
      </p>
    </div>
  </div>
  <div class="bio-picture lazyload" alt="people working">
  </div>
</div><br>

<section id="mision">
  <div class="one-on-one">
    <div class="lets-talk">
      <h1 class="talk-title">Misión</h1><br>
      <p class="mision">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vulputate ut pharetra sit amet aliquam id. Consequat interdum varius sit amet mattis. Metus vulputate eu scelerisque felis imperdiet proin. Posuere urna nec tincidunt praesent semper feugiat. Nunc eget lorem dolor sed viverra ipsum. Pulvinar mattis nunc sed blandit libero volutpat sed. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Ultrices neque ornare aenean euismod. Tincidunt nunc pulvinar sapien et ligula ullamcorper. Erat nam at lectus urna. Cursus euismod quis viverra nibh cras pulvinar mattis nunc. Nullam vehicula ipsum a arcu cursus vitae congue. Tellus molestie nunc non blandit massa enim nec. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at augue eget. Imperdiet nulla malesuada pellentesque elit eget gravida cum. Massa id neque aliquam vestibulum. Venenatis lectus magna fringilla urna porttitor rhoncus. Tincidunt id aliquet risus feugiat in. Cursus risus at ultrices mi tempus imperdiet.
      </p>
      <div class="border-bottom"></div>
      <h1 class="talk-title">Visión</h1><br>
      <p class="vision">
        Malesuada fames ac turpis egestas. Viverra ipsum nunc aliquet bibendum enim facilisis gravida. Lectus urna duis convallis convallis tellus id interdum velit. Posuere lorem ipsum dolor sit amet. Odio eu feugiat pretium nibh. Fames ac turpis egestas sed tempus urna et pharetra. Vitae et leo duis ut diam quam nulla porttitor. Et ligula ullamcorper malesuada proin libero nunc consequat interdum. Arcu bibendum at varius vel. Massa tincidunt dui ut ornare lectus sit amet est placerat. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Phasellus faucibus scelerisque eleifend donec pretium vulputate. Gravida cum sociis natoque penatibus et magnis. Integer vitae justo eget magna fermentum iaculis eu non diam. Velit scelerisque in dictum non consectetur. Imperdiet nulla malesuada pellentesque elit eget gravida cum.
      </p>
    </div>
  </div>
</section>

<section class="services-display" id="services-section">
  <div class="card card-width col-4">
    <header class="card-header">
      <p class="card-header-title">
        Service 1
      </p>
    </header>
    <div class="card-content">
      <div class="content">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nec iaculis mauris.
        <br>
        <time datetime="2016-1-1">11:09 PM - 1 Jan 2016</time>
      </div>
    </div>
    <footer class="card-footer">
      <a href="#contact-link" class="card-footer-item book-link">MÁS INFO</a>
    </footer>
  </div>

  <div class="card card-width col-4">
    <header class="card-header">
      <p class="card-header-title">
        Service 2
      </p>
    </header>
    <div class="card-content">
      <div class="content">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nec iaculis mauris.
        <br>
        <time datetime="2016-1-1">11:09 PM - 1 Jan 2016</time>
      </div>
    </div>
    <footer class="card-footer">
      <a href="#contact-link" class="card-footer-item book-link">MÁS INFO</a>
    </footer>
  </div>
  <div class="card card-width col-4">
    <header class="card-header">
      <p class="card-header-title">
        Service 3
      </p>
    </header>
    <div class="card-content">
      <div class="content">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nec iaculis mauris.
        <br>
        <time datetime="2016-1-1">11:09 PM - 1 Jan 2016</time>
      </div>
    </div>
    <footer class="card-footer">
      <a href="#contact-link" class="card-footer-item book-link">MÁS INFO</a>
    </footer>
  </div>


</section>

<div class="more-btn">
  <%= link_to "Ver más", productos_path, class: "card-footer-item book-link" %>
</div>

app/views/home/products.html.erb
<div class="prod-intro">
  <h1 class="fade-in">LOS PRODUCTOS QUE OFRECEMOS</h1>
</div>

<div class="prod-texto">
  <p class="fade-in">Distintos cedazos según las especificaciones del cliente, teniendo en cuenta los distintos elementos como lo son el tamaño del agujero, el diámetro del alambre, el tipo de tejido, el tipo de enganche y las dimensiones de la malla</p>
</div>

<%= render 'layouts/products_table.html.erb' %>

<div class="title center">
  <h1>Tipos de Tejidos</h1>
</div>

<div class="first-row">

  <div class="card" style="width: 18rem;">
    <img class="card-img-top" src="https://faveseca.s3.amazonaws.com/tejido1.png" alt="Tejido 1">
    <div class="card-body">
      <h5 class="card-title">Tejido 1</h5>
      <p class="card-text">Realizado con alambre ondulado. Gran rigidez, asegurando perfecta granulometría</p>
    </div>
  </div>

  <div class="card" style="width: 18rem;">
    <img class="card-img-top" src="https://faveseca.s3.amazonaws.com/tejido2.png" alt="Tejido 1">
    <div class="card-body">
      <h5 class="card-title">Tejido 2</h5>
      <p class="card-text">Realizado con alambre estampado en dos caras. Realiza un mejor cribado.</p>
    </div>
  </div>

  <div class="card" style="width: 18rem;">
    <img class="card-img-top" src="https://faveseca.s3.amazonaws.com/tejido3.png" alt="Tejido 1">
    <div class="card-body">
      <h5 class="card-title">Tejido 3</h5>
      <p class="card-text">Realizado con alambre estampado en una cara. Crea una superficie plana donde el material fluye fácilmente.</p>
    </div>
  </div>

</div>


<div class="second-row">
  <div class="card" style="width: 18rem;">
    <img class="card-img-top" src="https://faveseca.s3.amazonaws.com/tejido4.png" alt="Tejido 1">
    <div class="card-body">
      <h5 class="card-title">Tejido 4</h5>
      <p class="card-text">Realizado con alambre ondulado. La ligera vibración hace que sea auto limpiante.</p>
    </div>
  </div>

  <div class="card" style="width: 18rem;">
    <img class="card-img-top" src="https://faveseca.s3.amazonaws.com/tejido5.png" alt="Tejido 1">
    <div class="card-body">
      <h5 class="card-title">Tejido 5</h5>
      <p class="card-text">Realizado con alambre ondulado o estampado en dos caras. Se logra un incremento de área abierta.</p>
    </div>
  </div>
</div>

<div class="title center">
  <h1>Tipos de Enganche</h1>
</div>

<div class="first-row">
  <div class="card" style="width: 18rem;">
    <img src="https://faveseca.s3.amazonaws.com/enganche1.png" alt="Enganche 1" class="card-img-top">
    <div class="card-body">
      <h5 class="card-title">Enganche 1</h5>
      <p class="card-text">Extremos de cedazos doblados y protegidos exteriormente con lamina de 1.8mm de espesor (alambre 2mm en adelante)</p>
    </div>
  </div>

  <div class="card" style="width: 18rem;">
    <img src="https://faveseca.s3.amazonaws.com/enganche2.png" alt="Enganche 2" class="card-img-top">
    <div class="card-body">
      <h5 class="card-title">Enganche 2</h5>
      <p class="card-text">Extremo de cedazos doblado reforzado internamente con ángulo soldado (alambre 8mm en adelante)</p>
    </div>
  </div>

  <div class="card" style="width: 18rem;">
    <img src="https://faveseca.s3.amazonaws.com/enganche3.png" alt="Enganche 3" class="card-img-top">
    <div class="card-body">
      <h5 class="card-title">Enganche 3</h5>
      <p class="card-text">Ángulo de 6mm de espesor soldado externamente (alambre 8mm en adelante)</p>
    </div>
  </div>
</div>

app/views/layouts/_buy_form.html.erb
<%= form_for :contact, url: contacts_path do |f| %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer" id="contact-link">
  <div class="footer-info">
    <h1><strong><u>CONTACTO</u></strong></h1><br>
    <p>Calle 16 entre Av. 3 y 4 de la zona industrial 1<br>Barquisimeto, Lara, Venezuela</p><br>
    <a href="mailto:favececa2016@gmail.com">Email</a><br>
    <p> TEL: +58 2512374407</p><br>
    <p> TEL: +58 4245103864</p><br>
    <p> TEL: +58 4245177890</p><br>
  </div>

  <!-- <div class="footer-form">
    <div class="field">
      <label for="fullName" class="label">Full Name</label>
      <div>
        <input id="fullName" class="input" type="text" placeholder="e.g John Doe">
      </div>
    </div>

    <div class="field">
      <label for="email" class="label">Email *</label>
      <div>
        <input id="email" class="input" type="email" placeholder="e.g. johndoe@gmail.com">
      </div>
    </div>

    <div class="field">
      <label for="message" class="label">Message</label>
      <div>
        <textarea id="message" class="textarea" placeholder="What's your message"></textarea>
      </div>
    </div>

    <div>
      <button class="button is-primary" id="submit-btn">Submit</button>
    </div>
  </div> -->

</div>
<div class="signature">
  Website built by <a href="https://www.jmdevshop.com" target="_blank" rel="noopener noreferrer"><u>JM Dev, LLC<u></a>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar is-transparent">
    <div class="navbar-brand">
        <a class="navbar-item" href="https://bulma.io">
            <img src="https://bulma.io/images/bulma-logo.png" alt="Bulma: a modern CSS framework based on Flexbox" width="112" height="28">
        </a>
        <div class="navbar-burger" data-target="navbarExampleTransparentExample">
            <span></span>
            <span></span>
            <span></span>
        </div>
    </div>
    <div id="navbarExampleTransparentExample" class="navbar-menu">
        <div class="navbar-start">
            <a class="navbar-item" href="/">
                Inicio
            </a>
            <div class="navbar-item has-dropdown is-hoverable">
                <p class="navbar-link" disabled href="/">
                    Mas Información
                </p>
                <div class="navbar-dropdown is-boxed">
                  <a class="navbar-item" id="navbar-b" href="/#about-us-section">Sobre Nosotros</a>
                  <a class="navbar-item" id="navbar-c" href="/#mision">Misión y Visión</a>
                  <a class="navbar-item" id="navbar-d" href="/#services-section">Servicios</a>
                  <a class="navbar-item" id="navbar-e" href="/#contact-link">Contacto</a>
                </div>
            </div>
        </div>

        <div class="navbar-end">
            <div class="navbar-item">
                <div class="field is-grouped">

                </div>
            </div>
        </div>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
          <div class="field is-grouped">
              <p class="control">
                  <a class="bd-tw-button button" href="/productos">
                      <span>
                          Productos
                      </span>
                  </a>
              </p>
          </div>
      </div>
    </div>

</nav>

app/views/layouts/_products_table.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Agujero Cuadrado (pulg)</th>
      <th>Agujero Cuadrado (mm)</th>
      <th>Diametro Alambre (mm)</th>
      <th>Peso (kg / m2)</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td>1/8</td>
      <td>3,175</td>
      <td>2</td>
      <td>9,60</td>
    </tr>

    <tr>
      <td>5/32</td>
      <td>3,97</td>
      <td>2</td>
      <td>8,40</td>
    </tr>

    <tr>
      <td>3/16</td>
      <td>4,76</td>
      <td>2</td>
      <td>7,20</td>
    </tr>

    <tr>
      <td>1/4</td>
      <td>6,35</td>
      <td>3</td>
      <td>14,30</td>
    </tr>

    <tr>
      <td>5/16</td>
      <td>7,94</td>
      <td>4</td>
      <td>17,00</td>
    </tr>

    <tr>
      <td>3/8</td>
      <td>9.53</td>
      <td>4</td>
      <td>14,80</td>
    </tr>

    <tr>
      <td>3/8</td>
      <td>9,53</td>
      <td>5</td>
      <td>23,00</td>
    </tr>

    <tr>
      <td>7/16</td>
      <td>11,11</td>
      <td>5</td>
      <td>20,50</td>
    </tr>

    <tr>
      <td>1/2</td>
      <td>12,7</td>
      <td>5</td>
      <td>18,50</td>
    </tr>

    <tr>
      <td>9/16</td>
      <td>14,3</td>
      <td>6</td>
      <td>24,50</td>
    </tr>

    <tr>
      <td>5/8</td>
      <td>15,9</td>
      <td>6</td>
      <td>21,30</td>
    </tr>

    <tr>
      <td>3/4</td>
      <td>19,05</td>
      <td>6</td>
      <td>18,40</td>
    </tr>

    <tr>
      <td>3/4</td>
      <td>19,05</td>
      <td>7</td>
      <td>24,00</td>
    </tr>

    <tr>
      <td>7/8</td>
      <td>22,23</td>
      <td>7</td>
      <td>22,00</td>
    </tr>

    <tr>
      <td>7/8</td>
      <td>22,23</td>
      <td>8</td>
      <td>27,00</td>
    </tr>

    <tr>
      <td>1</td>
      <td>25,4</td>
      <td>8</td>
      <td>24,00</td>
    </tr>

    <tr>
      <td>1.1/8</td>
      <td>28,6</td>
      <td>8</td>
      <td>22,00</td>
    </tr>

    <tr>
      <td>1,1.4</td>
      <td>31,75</td>
      <td>8</td>
      <td>20,00</td>
    </tr>

    <tr>
      <td>1,1/2</td>
      <td>38,10</td>
      <td>8</td>
      <td>17,50</td>
    </tr>

    <tr>
      <td>1.5/8</td>
      <td>41,30</td>
      <td>8</td>
      <td>16,00</td>
    </tr>

    <tr>
      <td>1.3/4</td>
      <td>44,45</td>
      <td>8</td>
      <td>15,00</td>
    </tr>

    <tr>
      <td>2</td>
      <td>50,80</td>
      <td>8</td>
      <td>13,50</td>
    </tr>

    <tr>
      <td>1.1/2</td>
      <td>38,10</td>
      <td>10</td>
      <td>26,50</td>
    </tr>

    <tr>
      <td>1.5/8</td>
      <td>41,30</td>
      <td>10</td>
      <td>24,00</td>
    </tr>

    <tr>
      <td>2</td>
      <td>50,80</td>
      <td>10</td>
      <td>22,00</td>
    </tr>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Favececa</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="Description" content="template page for Favececa">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lazysizes/5.2.0/lazysizes.min.js" integrity="sha256-h2tMEmhemR2IN4wbbdNjj9LaDIjzwk2hralQwfJmBOE=" crossorigin="anonymous"></script>
</head>

<header>
    <%= render "layouts/navbar" %>
</header>

<body>
    <%= yield %>
</body>

<footer>
    <%= render "layouts/footer" %>
</footer>

</html>